// ui/src/App.tsx
function App() {
  return (
    <div className="d-flex align-items-center justify-content-center vh-100">
      <div className="text-center">
        <i className="bi bi-book fs-1 text-primary" aria-hidden="true" />
        <h1 className="mt-2">Skypiea</h1>
      </div>
    </div>
  );
}

export default App;

// ui/src/App.vue
<script setup lang="ts">
// Phase 1 scaffold: proves the Vue toolchain builds/runs/produces the entry-
// tag shape build-integrity.mjs expects. Replaced with the real routed app
// (ErrorBoundary + RouterView) in a later migration phase -- see CLAUDE.md.
</script>

<template>
  <div class="d-flex align-items-center justify-content-center vh-100">
    <span class="d-inline-flex align-items-center gap-2 fs-2">
      <i class="bi bi-book text-primary" aria-hidden="true" />
      <span class="fw-semibold">Skypiea</span>
    </span>
  </div>
</template>
