// ui/src/screens/Library/LibraryScreen.tsx
// Screen 2 -- Library (docs/ui.md): a catalog nav on the left, a plain list
// of books on the right. Top bar stays a slim strip above both panes:
// wordmark and a search field. Account status/actions (who's signed in, and
// locking the vault) live in the nav's account footer instead, not the top
// bar.
//
// Below lg, the nav has no room to sit beside the book list, so its content
// (NavItem lists) is shared between two renderings instead of duplicated:
// a persistent lg+ sidebar, and a dropdown below lg -- toggled by the book
// icon alone (not the full wordmark) rather than a separate hamburger
// button next to it.

import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";

import { BookmarkRow } from "../../components/BookmarkRow";
import { BookRow } from "../../components/BookRow";
import { DropdownToggleButton } from "../../components/DropdownToggleButton";
import { Wordmark } from "../../components/Wordmark";
import { useDropdown } from "../../hooks/useDropdown";
import { useVault } from "../../state/VaultContext";
import {
  allBooksSorted,
  browseEntries,
  booksForDimensionValue,
  matchesSearch,
  recentBookmarks,
  recentBooks,
  type BrowseDimension,
  type BrowseEntry,
  type LibraryBook,
  type RecentBookmarkItem,
} from "./libraryModel";
import { useLibraryBooks } from "./useLibraryBooks";

type View =
  | { kind: "recent" }
  | { kind: "all" }
  | { kind: "browse"; dimension: BrowseDimension }
  | { kind: "browseValue"; dimension: BrowseDimension; value: string };

const DIMENSION_LABEL: Record<BrowseDimension, string> = {
  author: "Authors",
  subject: "Subjects",
  publisher: "Publishers",
};

function NavItem({
  active,
  label,
  count,
  onClick,
}: {
  active: boolean;
  label: string;
  count: number;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      className={`list-group-item list-group-item-action d-flex justify-content-between align-items-center gap-2 ${active ? "active" : ""}`}
      onClick={onClick}
    >
      <span className="text-truncate">{label}</span>
      <span className={`flex-shrink-0 ${active ? "" : "text-body-secondary"}`}>{count}</span>
    </button>
  );
}

function LibraryNavContent({
  view,
  selectView,
  recentCount,
  allCount,
  authorEntries,
  subjectEntries,
  publisherEntries,
  displayName,
  onLock,
  onRefresh,
  refreshing,
}: {
  view: View;
  selectView: (next: View) => void;
  recentCount: number;
  allCount: number;
  authorEntries: BrowseEntry[];
  subjectEntries: BrowseEntry[];
  publisherEntries: BrowseEntry[];
  displayName: string | undefined;
  onLock: () => void;
  onRefresh: () => void;
  refreshing: boolean;
}) {
  return (
    <>
      <div className="flex-grow-1 overflow-auto">
        <div className="list-group list-group-flush">
          <NavItem
            active={view.kind === "recent"}
            label="Recent"
            count={recentCount}
            onClick={() => selectView({ kind: "recent" })}
          />
          <NavItem
            active={view.kind === "all"}
            label="All books"
            count={allCount}
            onClick={() => selectView({ kind: "all" })}
          />
        </div>
        <div className="text-body-secondary small fw-semibold text-uppercase mt-3 mb-1 px-2">Browse</div>
        <div className="list-group list-group-flush">
          <NavItem
            active={view.kind === "browse" && view.dimension === "author"}
            label="Authors"
            count={authorEntries.length}
            onClick={() => selectView({ kind: "browse", dimension: "author" })}
          />
          <NavItem
            active={view.kind === "browse" && view.dimension === "subject"}
            label="Subjects"
            count={subjectEntries.length}
            onClick={() => selectView({ kind: "browse", dimension: "subject" })}
          />
          <NavItem
            active={view.kind === "browse" && view.dimension === "publisher"}
            label="Publishers"
            count={publisherEntries.length}
            onClick={() => selectView({ kind: "browse", dimension: "publisher" })}
          />
        </div>
      </div>

      {/* The account footer: who's signed in, and the (now icon-only)
          Refresh/Lock actions -- moved here from the top bar so they're
          part of "your account" rather than sitting next to the search
          field. Refresh sits to Lock's left. */}
      <div className="border-top pt-2 mt-2 d-flex align-items-center justify-content-between gap-2">
        <span className="d-flex align-items-center gap-2 text-truncate">
          <i className="bi bi-person-circle text-body-secondary flex-shrink-0" aria-hidden="true" />
          <span className="small text-body-secondary text-truncate">{displayName}</span>
        </span>
        <span className="d-flex align-items-center gap-2 flex-shrink-0">
          <button
            type="button"
            className="btn btn-sm btn-outline-secondary border-primary flex-shrink-0"
            onClick={onRefresh}
            disabled={refreshing}
            aria-label="Refresh library"
            title="Refresh library"
          >
            {refreshing ? (
              <span className="spinner-border spinner-border-sm text-primary" role="status" aria-hidden="true" />
            ) : (
              <i className="bi bi-arrow-clockwise text-primary" aria-hidden="true" />
            )}
          </button>
          <button
            type="button"
            className="btn btn-sm btn-outline-secondary border-primary flex-shrink-0"
            onClick={onLock}
            aria-label="Lock"
            title="Lock"
          >
            <i className="bi bi-unlock text-primary" aria-hidden="true" />
          </button>
        </span>
      </div>
    </>
  );
}

export function LibraryScreen() {
  const { lock, refresh, refreshing, session, bookmarksMap, removeAccessEntry, removeBookmarkEntry } = useVault();
  const navigate = useNavigate();
  const { books, loading } = useLibraryBooks();
  const [view, setView] = useState<View>({ kind: "recent" });
  const [search, setSearch] = useState("");
  const [refreshError, setRefreshError] = useState<string | null>(null);

  async function handleRefresh() {
    setRefreshError(null);
    try {
      await refresh();
    } catch (err) {
      setRefreshError(err instanceof Error ? err.message : String(err));
    }
  }
  // Below the lg breakpoint the left nav collapses into the wordmark's
  // dropdown; picking anything in it closes it again so the chosen view
  // actually comes into view.
  const nav = useDropdown();

  function selectView(next: View) {
    setView(next);
    nav.close();
  }

  const authorEntries = useMemo(() => browseEntries(books ?? [], "author"), [books]);
  const subjectEntries = useMemo(() => browseEntries(books ?? [], "subject"), [books]);
  const publisherEntries = useMemo(() => browseEntries(books ?? [], "publisher"), [books]);
  const recent = useMemo(() => recentBooks(books ?? []), [books]);
  // Search only filters Continue Reading -- Recent Bookmarks isn't searchable.
  const continueReading = useMemo(
    () => (search.trim() ? recent.filter((b) => matchesSearch(b, search)) : recent),
    [recent, search],
  );
  const metadataById = useMemo(() => new Map((books ?? []).map((b) => [b.txtId, b.info])), [books]);
  const recentBookmarkItems = useMemo(() => recentBookmarks(bookmarksMap, metadataById), [bookmarksMap, metadataById]);

  function openBook(book: LibraryBook) {
    navigate(`/read/${book.txtId}`);
  }

  function openBookmark(item: RecentBookmarkItem) {
    navigate(`/read/${item.txtId}?part=${item.partNum}&line=${item.line}`);
  }

  let heading: string;
  let headingDetail: string;
  let bookList: LibraryBook[] | null = null;
  let browseList: { value: string; count: number }[] | null = null;

  if (view.kind === "recent") {
    heading = "Recent";
    // Every entry here has lastPartNum set (recentBooks() only includes
    // books with a lastAccessedMs, and the two are always set together --
    // see libraryModel.ts's buildLibraryBooks), so this is just its count.
    headingDetail = `${recent.length} in progress`;
  } else if (view.kind === "all") {
    const all = allBooksSorted(books ?? []);
    heading = "All books";
    headingDetail = `${all.length} book${all.length === 1 ? "" : "s"}`;
    bookList = all;
  } else if (view.kind === "browse") {
    const entries = { author: authorEntries, subject: subjectEntries, publisher: publisherEntries }[view.dimension];
    heading = DIMENSION_LABEL[view.dimension];
    headingDetail = `${entries.length}`;
    browseList = entries;
  } else {
    const filtered = booksForDimensionValue(books ?? [], view.dimension, view.value);
    heading = view.value;
    headingDetail = `${filtered.length} book${filtered.length === 1 ? "" : "s"}`;
    bookList = filtered;
  }

  if (bookList && search.trim()) {
    bookList = bookList.filter((b) => matchesSearch(b, search));
    // Recompute now that a search query may have shrunk bookList -- keeps
    // the header's count in sync with what's actually rendered below,
    // instead of showing the pre-search total.
    headingDetail = `${bookList.length} book${bookList.length === 1 ? "" : "s"}`;
  }

  return (
    <div className="shell-60 d-flex flex-column vh-100">
      {/* flex-nowrap, not flex-wrap: flexbox decides line breaks from each
          item's *hypothetical* (unshrunk) main size, not its post-shrink
          size -- so even with minWidth:0 below letting the content cell
          shrink, a wrapping container could still push it to a second line
          at viewport widths where its natural (un-shrunk) size doesn't fit
          next to the drawer toggle, before shrinking ever gets a chance to
          apply. Forcing one line makes that shrinking actually take effect,
          keeping the toggle and search box together at every width instead
          of wrapping at some in-between range. */}
      <div className="border-bottom d-flex flex-nowrap align-items-stretch">
        {/* lg+: a fixed-width cell -- same class (and width) as the sidebar
            below -- so the content cell beside it starts at the same x as
            the right pane's own content, and its border-end continues the
            sidebar's vertical rule upward into the top bar. .library-nav
            sets flex-direction:column (for the sidebar's own content-above-
            footer stacking), which flips align-items-center to a
            *horizontal* centering here -- justify-content-center is what
            actually centers the wordmark vertically in a column-direction
            flex container, since its main axis is now the vertical one. */}
        <div className="library-nav border-end p-2 d-none d-lg-flex align-items-center justify-content-center">
          <Wordmark />
        </div>

        {/* Below lg: the book icon alone (not the "Skypiea" text) is the
            drawer toggle -- styled as a visible bordered button so it reads
            as tappable; the wordmark text sits beside it, plain, but is
            dropped below sm entirely -- on a phone-width screen there isn't
            room for the icon, "Skypiea", and the search box on one line, and
            the icon (still labeled via aria-label) plus search box matter
            more than the wordmark text there. There's no fixed-width
            alignment cell here -- below lg there's no persistent sidebar for
            it to line up against. */}
        <div
          ref={nav.ref}
          className="dropdown position-relative d-lg-none d-flex align-items-center gap-2 ps-2 ps-sm-3 py-2"
        >
          <DropdownToggleButton
            open={nav.open}
            onClick={nav.toggle}
            icon="bi-book"
            ariaLabel="Library menu"
            className="d-flex align-items-center justify-content-center"
            disabled={refreshing}
          />
          <span className="fw-semibold d-none d-sm-inline">Skypiea</span>
          {nav.open && (
            <div
              className="dropdown-menu app-dropdown-menu app-dropdown-menu-start show p-2 d-flex flex-column"
              style={{ width: "16rem", maxWidth: "90vw", maxHeight: "70vh" }}
            >
              <LibraryNavContent
                view={view}
                selectView={selectView}
                recentCount={recent.length}
                allCount={(books ?? []).length}
                authorEntries={authorEntries}
                subjectEntries={subjectEntries}
                publisherEntries={publisherEntries}
                displayName={session?.creds.displayName}
                onLock={lock}
                onRefresh={() => void handleRefresh()}
                refreshing={refreshing}
              />
            </div>
          )}
        </div>

        {/* Content cell: same horizontal padding (px-3) as the right pane's
            own header row below, so the search bar's left edge lines up
            with the book list's heading/rows -- and at lg+ the input
            itself is capped to half this cell's width instead of
            stretching across the whole pane. */}
        <div className="flex-grow-1 d-flex align-items-center px-3 py-2" style={{ minWidth: 0 }}>
          <div className="position-relative search-bar-width">
            {/* The icon sits inside the input itself (absolutely
                positioned, padding-left on the input to make room) rather
                than Bootstrap's input-group, which renders it as its own
                bordered segment beside the input -- visually two joined
                boxes, not one. */}
            <i
              className="bi bi-search position-absolute top-50 start-0 translate-middle-y ms-3 text-body-secondary pe-none"
              aria-hidden="true"
            />
            <input
              type="search"
              className="form-control themed-control ps-5"
              placeholder="Search library"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              disabled={refreshing}
              aria-label="Search library"
            />
          </div>
        </div>
      </div>

      {refreshError && (
        <div className="alert alert-danger m-2 py-2 px-3 mb-0" role="alert">
          {refreshError}
        </div>
      )}

      {/*
        The sidebar only ever renders at lg+ now -- below that, the same
        content shows inside the wordmark's dropdown instead (top bar,
        above). At lg+, flex items default to min-width:auto, meaning a
        child won't shrink below its own content's intrinsic width even with
        overflow-hidden/text-truncate on a descendant -- so a long title/
        author/subject list in the right pane could otherwise demand more
        width than available and squeeze this fixed-width nav out of the
        way. The right pane gets minWidth:0 below (let its own long content
        actually truncate instead of forcing extra width).
      */}
      <div className="flex-grow-1 d-flex flex-column flex-lg-row overflow-hidden">
        {/* Refreshing replaces this entire region -- the lg+ sidebar
            (everything below the "Skypiea" wordmark: nav items, account
            footer, Lock/Refresh included) and the content pane alike --
            with one centered spinner. Only the top bar (wordmark/toggle,
            already-disabled search box) stays as it was; the below-lg
            dropdown copy of the nav is untouched too, since it isn't part
            of this persistent lg+ region at all. */}
        {refreshing ? (
          <div className="flex-grow-1 d-flex align-items-center justify-content-center">
            <div className="spinner-border text-primary" role="status">
              <span className="visually-hidden">Refreshing your library…</span>
            </div>
          </div>
        ) : (
          <>
            <div className="library-nav border-end p-2 d-none d-lg-flex">
              <LibraryNavContent
                view={view}
                selectView={selectView}
                recentCount={recent.length}
                allCount={(books ?? []).length}
                authorEntries={authorEntries}
                subjectEntries={subjectEntries}
                publisherEntries={publisherEntries}
                displayName={session?.creds.displayName}
                onLock={lock}
                onRefresh={() => void handleRefresh()}
                refreshing={refreshing}
              />
            </div>

            <div className="flex-grow-1 d-flex flex-column overflow-hidden" style={{ minWidth: 0 }}>
              <div className="d-flex justify-content-between align-items-baseline px-3 py-2 border-bottom">
                <h2 className="h6 mb-0">{heading}</h2>
                <span className="small text-body-secondary">{headingDetail}</span>
              </div>

              <div className="flex-grow-1 overflow-auto">
                {loading && <p className="text-body-secondary p-3">Loading your library…</p>}

                {!loading && view.kind === "recent" && (
                  <>
                    <div className="small text-body-secondary text-uppercase fw-semibold px-3 pt-3 pb-1">
                      Continue Reading
                    </div>
                    <div className="list-group list-group-flush">
                      {continueReading.map((book) => (
                        <BookRow
                          key={book.txtId}
                          book={book}
                          onClick={() => openBook(book)}
                          onDelete={() => void removeAccessEntry(book.txtId)}
                          hidePartNum
                        />
                      ))}
                      {continueReading.length === 0 && (
                        <p className="text-body-secondary px-3 pb-3">No books in progress yet.</p>
                      )}
                    </div>

                    <div className="small text-body-secondary text-uppercase fw-semibold px-3 pt-4 pb-1">
                      Recent Bookmarks
                    </div>
                    <div className="list-group list-group-flush">
                      {recentBookmarkItems.map((item) => (
                        <BookmarkRow
                          key={`${item.txtId}-${item.createdAt}`}
                          title={item.info.title}
                          partNum={item.partNum}
                          line={item.line}
                          txtPreview={item.txtPreview}
                          onClick={() => openBookmark(item)}
                          onDelete={() => void removeBookmarkEntry(item.txtId, item.createdAt)}
                          deleteAriaLabel={`Remove this bookmark in ${item.info.title}`}
                        />
                      ))}
                      {recentBookmarkItems.length === 0 && (
                        <p className="text-body-secondary px-3 pb-3">No bookmarks yet.</p>
                      )}
                    </div>
                  </>
                )}

                {!loading && view.kind !== "recent" && browseList && (
                  <div className="list-group list-group-flush">
                    {browseList.map((entry) => (
                      <button
                        key={entry.value}
                        type="button"
                        className="list-group-item list-group-item-action d-flex justify-content-between align-items-center"
                        onClick={() =>
                          selectView({
                            kind: "browseValue",
                            dimension: (view as { dimension: BrowseDimension }).dimension,
                            value: entry.value,
                          })
                        }
                      >
                        <span className="text-truncate" style={{ minWidth: 0 }}>
                          {entry.value}
                        </span>
                        <span className="text-body-secondary flex-shrink-0 ms-2">{entry.count}</span>
                      </button>
                    ))}
                    {browseList.length === 0 && <p className="text-body-secondary p-3">Nothing here yet.</p>}
                  </div>
                )}

                {!loading && view.kind !== "recent" && bookList && (
                  <div className="list-group list-group-flush">
                    {bookList.map((book) => (
                      <BookRow key={book.txtId} book={book} onClick={() => openBook(book)} />
                    ))}
                    {bookList.length === 0 && <p className="text-body-secondary p-3">No books match here yet.</p>}
                  </div>
                )}
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

// ui/src/screens/Library/LibraryScreen.vue
<script setup lang="ts">
// Screen 2 -- Library (docs/ui.md): a catalog nav on the left, a plain list
// of books on the right. Top bar stays a slim strip above both panes:
// wordmark and a search field. Account status/actions (who's signed in, and
// locking the vault) live in the nav's account footer instead, not the top
// bar.
//
// Below lg, the nav has no room to sit beside the book list, so its content
// (LibraryNavContent) is shared between two renderings instead of
// duplicated: a persistent lg+ sidebar, and a dropdown below lg -- toggled
// by the book icon alone (not the full wordmark) rather than a separate
// hamburger button next to it.

import { computed, ref } from "vue";
import { useRouter } from "vue-router";

import BookmarkRow from "../../components/BookmarkRow.vue";
import BookRow from "../../components/BookRow.vue";
import DropdownToggleButton from "../../components/DropdownToggleButton.vue";
import Wordmark from "../../components/Wordmark.vue";
import { useDropdown } from "../../composables/useDropdown";
import { useVault } from "../../state/vault";
import {
  allBooksSorted,
  browseEntries,
  booksForDimensionValue,
  matchesSearch,
  recentBookmarks,
  recentBooks,
  type BrowseDimension,
  type LibraryBook,
  type RecentBookmarkItem,
} from "./libraryModel";
import { useLibraryBooks } from "./composables/useLibraryBooks";
import LibraryNavContent, { type View } from "./LibraryNavContent.vue";

const DIMENSION_LABEL: Record<BrowseDimension, string> = {
  author: "Authors",
  subject: "Subjects",
  publisher: "Publishers",
};

const { lock, session, bookmarksMap, removeAccessEntry, removeBookmarkEntry } = useVault();
const router = useRouter();
const { books, loading } = useLibraryBooks();
const view = ref<View>({ kind: "recent" });
const search = ref("");
// Below the lg breakpoint the left nav collapses into the wordmark's
// dropdown; picking anything in it closes it again so the chosen view
// actually comes into view.
const nav = useDropdown();

function selectView(next: View): void {
  view.value = next;
  nav.close();
}

const authorEntries = computed(() => browseEntries(books.value ?? [], "author"));
const subjectEntries = computed(() => browseEntries(books.value ?? [], "subject"));
const publisherEntries = computed(() => browseEntries(books.value ?? [], "publisher"));
const recent = computed(() => recentBooks(books.value ?? []));
// Search only filters Continue Reading -- Recent Bookmarks isn't searchable.
const continueReading = computed(() =>
  search.value.trim() ? recent.value.filter((b) => matchesSearch(b, search.value)) : recent.value,
);
const metadataById = computed(() => new Map((books.value ?? []).map((b) => [b.txtId, b.info])));
const recentBookmarkItems = computed(() => recentBookmarks(bookmarksMap.value, metadataById.value));

function openBook(book: LibraryBook): void {
  router.push(`/read/${book.txtId}`);
}

function openBookmark(item: RecentBookmarkItem): void {
  router.push(`/read/${item.txtId}?part=${item.partNum}&line=${item.line}`);
}

// Mirrors LibraryScreen.tsx's own sequential if/else derivation exactly:
// first pick heading/headingDetail/bookList/browseList from `view`, then --
// only when bookList is a real list -- apply the search filter and
// recompute headingDetail from what's actually left, so the header's count
// never shows the pre-search total.
const viewData = computed(() => {
  const v = view.value;
  const allBooks = books.value ?? [];
  let heading: string;
  let headingDetail: string;
  let bookList: LibraryBook[] | null = null;
  let browseList: { value: string; count: number }[] | null = null;

  if (v.kind === "recent") {
    heading = "Recent";
    // Every entry here has lastPartNum set (recentBooks() only includes
    // books with a lastAccessedMs, and the two are always set together --
    // see libraryModel.ts's buildLibraryBooks), so this is just its count.
    headingDetail = `${recent.value.length} in progress`;
  } else if (v.kind === "all") {
    const all = allBooksSorted(allBooks);
    heading = "All books";
    headingDetail = `${all.length} book${all.length === 1 ? "" : "s"}`;
    bookList = all;
  } else if (v.kind === "browse") {
    const entries = { author: authorEntries.value, subject: subjectEntries.value, publisher: publisherEntries.value }[
      v.dimension
    ];
    heading = DIMENSION_LABEL[v.dimension];
    headingDetail = `${entries.length}`;
    browseList = entries;
  } else {
    const filtered = booksForDimensionValue(allBooks, v.dimension, v.value);
    heading = v.value;
    headingDetail = `${filtered.length} book${filtered.length === 1 ? "" : "s"}`;
    bookList = filtered;
  }

  if (bookList && search.value.trim()) {
    bookList = bookList.filter((b) => matchesSearch(b, search.value));
    headingDetail = `${bookList.length} book${bookList.length === 1 ? "" : "s"}`;
  }

  return { heading, headingDetail, bookList, browseList };
});
</script>

<template>
  <div class="shell-60 d-flex flex-column vh-100">
    <!-- flex-nowrap, not flex-wrap: flexbox decides line breaks from each
         item's *hypothetical* (unshrunk) main size, not its post-shrink
         size -- so even with minWidth:0 below letting the content cell
         shrink, a wrapping container could still push it to a second line
         at viewport widths where its natural (un-shrunk) size doesn't fit
         next to the drawer toggle, before shrinking ever gets a chance to
         apply. Forcing one line makes that shrinking actually take effect,
         keeping the toggle and search box together at every width instead
         of wrapping at some in-between range. -->
    <div class="border-bottom d-flex flex-nowrap align-items-stretch">
      <!-- lg+: a fixed-width cell -- same class (and width) as the sidebar
           below -- so the content cell beside it starts at the same x as
           the right pane's own content, and its border-end continues the
           sidebar's vertical rule upward into the top bar. -->
      <div class="library-nav border-end p-2 d-none d-lg-flex align-items-center justify-content-center">
        <Wordmark />
      </div>

      <!-- Below lg: the book icon alone (not the "Skypiea" text) is the
           drawer toggle -- styled as a visible bordered button so it reads
           as tappable; the wordmark text sits beside it, plain, but is
           dropped below sm entirely. -->
      <div
        :ref="(el) => (nav.ref.value = el as HTMLElement | null)"
        class="dropdown position-relative d-lg-none d-flex align-items-center gap-2 ps-2 ps-sm-3 py-2"
      >
        <DropdownToggleButton
          :open="nav.open.value"
          :onClick="nav.toggle"
          icon="bi-book"
          ariaLabel="Library menu"
          className="d-flex align-items-center justify-content-center"
        />
        <span class="fw-semibold d-none d-sm-inline">Skypiea</span>
        <div
          v-if="nav.open.value"
          class="dropdown-menu app-dropdown-menu app-dropdown-menu-start show p-2 d-flex flex-column"
          style="width: 16rem; max-width: 90vw; max-height: 70vh"
        >
          <LibraryNavContent
            :view="view"
            :selectView="selectView"
            :recentCount="recent.length"
            :allCount="(books ?? []).length"
            :authorEntries="authorEntries"
            :subjectEntries="subjectEntries"
            :publisherEntries="publisherEntries"
            :displayName="session?.creds.displayName"
            :onLock="lock"
          />
        </div>
      </div>

      <!-- Content cell: same horizontal padding (px-3) as the right pane's
           own header row below, so the search bar's left edge lines up
           with the book list's heading/rows. -->
      <div class="flex-grow-1 d-flex align-items-center px-3 py-2" style="min-width: 0">
        <div class="position-relative search-bar-width">
          <i
            class="bi bi-search position-absolute top-50 start-0 translate-middle-y ms-3 text-body-secondary pe-none"
            aria-hidden="true"
          />
          <input
            type="search"
            class="form-control themed-control ps-5"
            placeholder="Search library"
            v-model="search"
            aria-label="Search library"
          />
        </div>
      </div>
    </div>

    <div class="flex-grow-1 d-flex flex-column flex-lg-row overflow-hidden">
      <div class="library-nav border-end p-2 d-none d-lg-flex">
        <LibraryNavContent
          :view="view"
          :selectView="selectView"
          :recentCount="recent.length"
          :allCount="(books ?? []).length"
          :authorEntries="authorEntries"
          :subjectEntries="subjectEntries"
          :publisherEntries="publisherEntries"
          :displayName="session?.creds.displayName"
          :onLock="lock"
        />
      </div>

      <div class="flex-grow-1 d-flex flex-column overflow-hidden" style="min-width: 0">
        <div class="d-flex justify-content-between align-items-baseline px-3 py-2 border-bottom">
          <h2 class="h6 mb-0">{{ viewData.heading }}</h2>
          <span class="small text-body-secondary">{{ viewData.headingDetail }}</span>
        </div>

        <div class="flex-grow-1 overflow-auto">
          <p v-if="loading" class="text-body-secondary p-3">Loading your library…</p>

          <template v-if="!loading && view.kind === 'recent'">
            <div class="small text-body-secondary text-uppercase fw-semibold px-3 pt-3 pb-1">Continue Reading</div>
            <div class="list-group list-group-flush">
              <BookRow
                v-for="book in continueReading"
                :key="book.txtId"
                :book="book"
                :onClick="() => openBook(book)"
                :onDelete="() => void removeAccessEntry(book.txtId)"
                hidePartNum
              />
              <p v-if="continueReading.length === 0" class="text-body-secondary px-3 pb-3">No books in progress yet.</p>
            </div>

            <div class="small text-body-secondary text-uppercase fw-semibold px-3 pt-4 pb-1">Recent Bookmarks</div>
            <div class="list-group list-group-flush">
              <BookmarkRow
                v-for="item in recentBookmarkItems"
                :key="`${item.txtId}-${item.createdAt}`"
                :title="item.info.title"
                :partNum="item.partNum"
                :line="item.line"
                :txtPreview="item.txtPreview"
                :onClick="() => openBookmark(item)"
                :onDelete="() => void removeBookmarkEntry(item.txtId, item.createdAt)"
                :deleteAriaLabel="`Remove this bookmark in ${item.info.title}`"
              />
              <p v-if="recentBookmarkItems.length === 0" class="text-body-secondary px-3 pb-3">No bookmarks yet.</p>
            </div>
          </template>

          <div v-if="!loading && view.kind !== 'recent' && viewData.browseList" class="list-group list-group-flush">
            <button
              v-for="entry in viewData.browseList"
              :key="entry.value"
              type="button"
              class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"
              @click="
                selectView({
                  kind: 'browseValue',
                  dimension: (view as { dimension: BrowseDimension }).dimension,
                  value: entry.value,
                })
              "
            >
              <span class="text-truncate" style="min-width: 0">{{ entry.value }}</span>
              <span class="text-body-secondary flex-shrink-0 ms-2">{{ entry.count }}</span>
            </button>
            <p v-if="viewData.browseList.length === 0" class="text-body-secondary p-3">Nothing here yet.</p>
          </div>

          <div v-if="!loading && view.kind !== 'recent' && viewData.bookList" class="list-group list-group-flush">
            <BookRow v-for="book in viewData.bookList" :key="book.txtId" :book="book" :onClick="() => openBook(book)" />
            <p v-if="viewData.bookList.length === 0" class="text-body-secondary p-3">No books match here yet.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
